//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurriculosGroup
    {
        public int Id { get; set; }
        public int GroupId { get; set; }
        public int CurriculoId { get; set; }
    
        public virtual Curriculos Curriculos { get; set; }
        public virtual Group Group { get; set; }
    }
}
