//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace TCC_MVC.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TCC_LUCASEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TCC_LUCASEntities object using the connection string found in the 'TCC_LUCASEntities' section of the application configuration file.
        /// </summary>
        public TCC_LUCASEntities() : base("name=TCC_LUCASEntities", "TCC_LUCASEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TCC_LUCASEntities object.
        /// </summary>
        public TCC_LUCASEntities(string connectionString) : base(connectionString, "TCC_LUCASEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TCC_LUCASEntities object.
        /// </summary>
        public TCC_LUCASEntities(EntityConnection connection) : base(connection, "TCC_LUCASEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Curriculos> Curriculos
        {
            get
            {
                if ((_Curriculos == null))
                {
                    _Curriculos = base.CreateObjectSet<Curriculos>("Curriculos");
                }
                return _Curriculos;
            }
        }
        private ObjectSet<Curriculos> _Curriculos;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Curriculos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCurriculos(Curriculos curriculos)
        {
            base.AddObject("Curriculos", curriculos);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TCC_LUCASModel", Name="Curriculos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Curriculos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Curriculos object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="data">Initial value of the Data property.</param>
        /// <param name="working">Initial value of the Working property.</param>
        /// <param name="updatedIn">Initial value of the UpdatedIn property.</param>
        public static Curriculos CreateCurriculos(global::System.Int32 id, global::System.String data, global::System.Boolean working, global::System.DateTime updatedIn)
        {
            Curriculos curriculos = new Curriculos();
            curriculos.Id = id;
            curriculos.Data = data;
            curriculos.Working = working;
            curriculos.UpdatedIn = updatedIn;
            return curriculos;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Data
        {
            get
            {
                return _Data;
            }
            set
            {
                if (_Data != value)
                {
                    OnDataChanging(value);
                    ReportPropertyChanging("Data");
                    _Data = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Data");
                    OnDataChanged();
                }
            }
        }
        private global::System.String _Data;
        partial void OnDataChanging(global::System.String value);
        partial void OnDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Working
        {
            get
            {
                return _Working;
            }
            set
            {
                if (_Working != value)
                {
                    OnWorkingChanging(value);
                    ReportPropertyChanging("Working");
                    _Working = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Working");
                    OnWorkingChanged();
                }
            }
        }
        private global::System.Boolean _Working;
        partial void OnWorkingChanging(global::System.Boolean value);
        partial void OnWorkingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime UpdatedIn
        {
            get
            {
                return _UpdatedIn;
            }
            set
            {
                if (_UpdatedIn != value)
                {
                    OnUpdatedInChanging(value);
                    ReportPropertyChanging("UpdatedIn");
                    _UpdatedIn = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UpdatedIn");
                    OnUpdatedInChanged();
                }
            }
        }
        private global::System.DateTime _UpdatedIn;
        partial void OnUpdatedInChanging(global::System.DateTime value);
        partial void OnUpdatedInChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion
    
    }

    #endregion
    
}
