//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Line
    {
        public Line()
        {
            this.CurriculosLine = new HashSet<CurriculosLine>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int AreaId { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual ICollection<CurriculosLine> CurriculosLine { get; set; }
    }
}
