//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TCC_LUCASEntities : DbContext
    {
        public TCC_LUCASEntities()
            : base("name=TCC_LUCASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Curriculos> Curriculos { get; set; }
        public DbSet<CurriculosGroup> CurriculosGroup { get; set; }
        public DbSet<Group> Group { get; set; }
        public DbSet<QualisConference> QualisConference { get; set; }
        public DbSet<QualisPeriodico> QualisPeriodico { get; set; }
    }
}
